fashion/apps/photographers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = 'photographers'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:album_id>/', views.detail, name = 'detail'),
    path('addalbum/',  views.add_album, name='add_album'),
    path('<int:album_id>/editalbum/', views.edit_album, name = 'edit_album'),
    path('<int:album_id>/delete/<int:photo_id>/', views.delete_photo, name = 'delete_photo'),
    path('<int:album_id>/add_photo/', views.add_photo, name = 'add_photo'),
    path('<int:album_id>/delete_album/', views.delete_album, name = 'delete_album')

]

# if settings.DEBUG:
#     if settings.MEDIA_ROOT:
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# urlpatterns += staticfiles_urlpatterns()

fashion/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

from fashion import settings
from fashion.apps.accounts import views

urlpatterns = [

    path('articles/', include('articles.urls'), name = 'home'),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('photographers/', include('photographers.urls'))
]
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashion/apps/photographers/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Photographer(models.Model):
    photographer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    discription = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        indexes = [
            models.Index(fields=['photographer']),
        ]

class Photo(models.Model):
    photo_album = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    #photo_image = models.ImageField(upload_to='media', blank=True)
    photo_image = models.TextField()
    photo_name = models.CharField(max_length=100)

    def __str__(self):
        return (self.photo_name)

fashion/apps/photographers/forms.py
from django import forms
from .models import Photographer, Photo

class PostForm(forms.ModelForm):
    class Meta:
        model = Photographer
        fields = ('name', 'discription',)

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('photo_image', 'photo_name', )

fashion/apps/photographers/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Photographer, Photo
from .forms import PostForm, PhotoForm
# Create your views here.

def index(request):
    photographers_list = Photographer.objects.all().order_by('-id')[:5]
    return (render(request, 'photographers/photographer_list.html', {'photographers_list' : photographers_list}))

def detail (request, album_id):
    album = Photographer.objects.get(id = album_id)
    photo_list = album.photo_set.all()
    return (render(request,'photographers/detail.html', {'album' : album, 'photo_list' : photo_list} ))

def add_album(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.photographer = request.user
            post.published_date = datetime.now()
            post.save()
            return HttpResponseRedirect(reverse('photographers:index' ))
    else:
        form = PostForm()
    return render(request, 'photographers/add_album.html', {'form': form})

def edit_album(request, album_id):
    post = get_object_or_404(Photographer, id = album_id)
    form = PostForm(request.POST, instance=post)
    if (request.method == "POST"):
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.photographer = request.user
            post.published_date = datetime.now()
            post.save()
            photographers_list = Photographer.objects.all().order_by('-id')[:5]
            return (render(request, 'photographers/photographer_list.html', {'photographers_list' : photographers_list}))
        else:
            form = PostForm(instance = post)
    return render(request, 'photographers/edit_album.html', {'form' : form, 'album' : post})

def delete_photo(request, album_id, photo_id):
    photo = Photo.objects.get(id = photo_id)
    if (photo.photo_album.photographer == request.user):
        photo.delete()
    return HttpResponseRedirect(reverse('photographers:detail', args = (album_id, )))

def delete_album(request, album_id):
    album = Photographer.objects.get(id = album_id)
    if (request.user == album.photographer):
        album.delete()
    return HttpResponseRedirect(reverse('photographers:index'))

def add_photo(request, album_id):
    album = Photographer.objects.get(id = album_id)
    if request.method == "POST":
        form = PhotoForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.photo_album = album
            post.save()
            return HttpResponseRedirect(reverse('photographers:detail', args = (album_id, ) ))
    else:
        form = PhotoForm()
    return render(request, 'photographers/add_photos.html', {'form': form, 'album': album})

templates/photographers/add_album.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Add album{% endblock %}
</head>
{% block content %}
    {% if request.user.is_authenticated %}
        <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>



{% endif %}
{% endblock %}
</html>

templates/photographers/add_photos.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add photo</title>
</head>
{% block content %}
<p>Загрузите фотографию в коллекцию</p>
    {% if request.user == album.photographer  %}
        <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        </form>
    {% else %}
        <p>Вы не можете изменять альбомы других пользователей</p>
    {% endif %}

{% endblock %}
</html>

templates/photographers/detail.html
{% extends 'index.html' %}

    {% block title %}{{ album.name }}{% endblock %}
<style>
   .fig {
    display: block; /* Блочный элемент (для старых браузеров) */
    text-align: center; /* Выравнивание по центру */
    font-style: italic; /* Курсивное начертание */
    margin-top: 0; /* Отступ сверху */
    margin-bottom: 5px; /* Отступ снизу */
    color: #666; /* Цвет подрисуночной подписи */
   }
  </style>
{% block content %}
    <h2 style = "color: #ff9400">{{ album.name }}</h2>
    <p>{{ album.discription }}</p>
    {% if request.user == album.photographer %}
        <p><a href = "{% url 'photographers:edit_album' album.id %}">Изменить альбом</a> <a href = "{% url 'photographers:delete_album' album.id %}">Удалить альбом</a></p>
    {% endif %}

    {% if photo_list %}
        {% for c in photo_list %}

                <p align="center"> <img src="{{ c.photo_image }}" alt = "{{ c.image.name }}" width = "300"></p>
                <h4 style="color: #828282" align="center">{{ c.photo_name }}</h4>

            {% if request.user == album.photographer %}
                <p align="right"><a href="{% url 'photographers:delete_photo' album.id c.id %}">Удалить фото</a></p>
            {% endif %}
        {% endfor %}
{% endif %}
{% if request.user == album.photographer %}
    <p align="center"><a href = "{% url 'photographers:add_photo' album.id %}">Добавить фотографии</a></p>
    {% endif %}
{% endblock %}
</html>

templates/photographers/edit_album.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Edit album{% endblock %}
</head>
{% block content %}
    {% if request.user.is_authenticated and request.user == album.photographer %}
        <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
        {% else %}
        <p>Вы не можете изменять альбомы других пользователей</p>
{% endif %}
{% endblock %}


</html>

templates/photographers/photographer_list.html
{% extends 'index.html' %}


    {% block title %}Коллекции{% endblock %}

{% block content %}
<div class="page-header">


    {% if request.user.is_authenticated %}
        <p align="center"> <a href="{% url 'photographers:add_album'  %}" class="top-menu"> Добавить альбом </a></p>
    {% endif %}
</div>

    {% if photographers_list %}
        {% for c in photographers_list %}
            <a  style="color: #ff9400" href = "{% url 'photographers:detail' c.id %}">{{ c.name }}</a>
            <h4 style="color: #828282">{{ c.discription }}</h4>
        {% endfor %}
    {% endif %}
{% endblock %}


</html>